# Generated by Django 4.1.2 on 2022-10-12 11:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Must be in format +(243)9999999999', max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Must be in format +(243)9999999999', max_length=128, region=None, unique=True),
        ),
    ]
