# Generated by Django 4.1 on 2022-10-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotel', '0002_alter_booking_check_in_alter_booking_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_blog_absact',
            name='image',
            field=models.ImageField(default='ok', upload_to='images/'),
            preserve_default=False,
        ),
    ]
