# Generated by Django 4.1.2 on 2022-10-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotel', '0002_alter_contact_phone_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_guest',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
