# Generated by Django 4.1 on 2022-10-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotel', '0004_room_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='achille@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='achille', max_length=50),
            preserve_default=False,
        ),
    ]
