# Generated by Django 4.1 on 2022-10-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotel', '0005_comment_email_comment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created', 'name', 'email')},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name', 'birth_date', 'phone', 'email', 'type_user']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('title', 'price', 'size', 'capacity', 'bed', 'published', 'status', 'image')},
        ),
        migrations.AlterModelOptions(
            name='room_blog_absact',
            options={'ordering': ['title', 'published', 'status', 'image']},
        ),
    ]
