# Generated by Django 4.1.2 on 2022-10-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotel', '0008_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='room_blog',
            new_name='category',
        ),
    ]
