# Generated by Django 4.1.2 on 2022-10-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotel', '0009_rename_room_blog_blog_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Reservation',
        ),
    ]
